# Generated by Django 3.2 on 2022-03-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loqui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Loqui',
                'verbose_name_plural': 'Loquis',
            },
        ),
    ]
