# Generated by Django 3.2 on 2022-03-14 23:46

from django.db import migrations
import json


poly_json = """
    {
        "type": "Feature",
        "geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [7.5051263961617565, 9.101143146458085],
                    [7.5009779128849345, 9.10006111478225],
                    [7.496868566243904, 9.099017723996113],
                    [7.491545983925931, 9.099983826680713],
                    [7.4925635364279515, 9.09727873259071],
                    [7.491428574022677, 9.094380394800368],
                    [7.501017049519362, 9.093878013863915],
                    [7.509118332899476, 9.095230576318201],
                    [7.5051263961617565, 9.101143146458085]
                ]
            ]
        }
    }
"""


def generate_data_for_location(apps, schema_editor):
    Location = apps.get_model('location', 'Location')
    Location.objects.create(
        latitude=9.097843,
        longitude=7.500430,
        polygon=json.loads(poly_json),
        phone=234987234987,
        address='Springfield avenue #2344'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_location'),
    ]

    operations = [
        migrations.RunPython(generate_data_for_location)
    ]
