# Generated by Django 3.2 on 2022-03-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20220314_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='polygon',
            field=models.JSONField(help_text='label for polygon '),
        ),
    ]
