# Generated by Django 3.2 on 2022-03-15 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='zoom',
            field=models.IntegerField(default=13, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(22)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='polygon',
            field=models.JSONField(help_text='\n            To change the delivery area (polygon), change the coordinates inside "coordinates". \n            For example, [lon1, lat1], [lon2, lat2], [lon3, lat3]... [lon1,lat1]\n        '),
        ),
    ]
