# Generated by Django 3.2 on 2022-03-14 00:54

from django.db import migrations
# from pyrfc3339 import generate


# custom script
# provides initial data for 'Contactcontent' model
def generateContactContent(apps, schema_editor): 
    Contactcontent = apps.get_model('contact', 'Contactcontent')
    Contactcontent.objects.create(
        title='Lorem ipsum dolor sit.',
        content='Ipsum dolor sit amet consectetur adipisicing elit. Molestiae aliquid fugit voluptatem, nihil autem at eius quod officiis, et architecto dolores sapiente earum, odit iure alias! Modi lorem it bumk blanditiis aliquam architecto!',
    )

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generateContactContent),
    ]
