# Generated by Django 3.2 on 2022-03-15 04:03

from django.db import migrations
from django.core.files import File 
from django.conf import settings 
from home.models import Homecontent
import os


path1 = os.path.join(settings.BASE_DIR, 'media/initialimages/slide1.jpg')
path2 = os.path.join(settings.BASE_DIR, 'media/initialimages/slide2.jpg')

def generate_home_content(apps, schema_editor): 
    with open(path1, 'rb') as f1, open(path2, 'rb') as f2: 
        Homecontent = apps.get_model('home', 'Homecontent')

        Homecontent.objects.create(
            welcomeline = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis, ipsa?',
            menuline = 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum earum neque, sint amet sequi culpa commodi, placeat quo dolor, error fugit odit maxime. Non deserunt beatae reiciendis? Debitis, necessitatibus veritatis',
            titleslideone = 'Porem ipsum dolor sit amet',
            descriptionslideone = 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit ipsum quod et eum facilis. Ullam necessitatibus autem doloribus illo voluptatibus.',
            imageslideone = File(f1, 'slide1.jpg'),
            titleslidetwo = 'Porem ipsum dolor sit amet',
            descriptionslidetwo = 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit ipsum quod et eum facilis. Ullam necessitatibus autem doloribus illo voluptatibus.',
            imageslidetwo = File(f2, 'slide2.jpg'),
            facebooklink = '#',
            youtubelink = '#',
            instagramlink = '#',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecontent'),
    ]

    operations = [
        migrations.RunPython(generate_home_content)
    ]
