# Generated by Django 3.2 on 2022-03-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220315_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapboxtoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Mapboxtoken',
                'verbose_name_plural': 'Mapbox token',
            },
        ),
    ]
