# Generated by Django 3.2 on 2022-03-19 01:27

from django.db import migrations


def generate_fake_mapbox_token(apps, schema_editor): 
    Mapboxtoken = apps.get_model('home', 'Mapboxtoken')
    Mapboxtoken.objects.create(
        token='YOUR-MAPBOX-TOKEN',
    )

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mapboxtoken'),
    ]

    operations = [
        migrations.RunPython(generate_fake_mapbox_token)
    ]
